---
sidebar: sidebar 
permalink: using-row-compare.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, Active IQ, Interop, Advisor, tool 
summary: Molte righe contengono informazioni molto simili in Interoperability Matrix Tool e può diventare un noioso processo manuale per trovare la differenza tra le righe. 
---
= USA confronto righe
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Molte righe contengono informazioni molto simili in Interoperability Matrix Tool e può diventare un noioso processo manuale per trovare la differenza tra le righe. Interoperability Matrix Tool fornisce una funzione per confrontare due righe.



== A proposito di questa attività

Nella pagina dei risultati, ogni soluzione ospita il pulsante Aggiungi a confronto o un'icona sull'intestazione della scheda di configurazione.



== Fasi

. Per aggiungere la configurazione per il confronto, fare clic sull'icona *Configurazione confronto componenti*. È possibile selezionare un massimo di due configurazioni da confrontare.
. Fare clic sul pulsante *Configurazione confronto componenti* per confrontare due righe.




== Risultato

Le differenze sono evidenziate in carattere *Bold* nella casella di visualizzazione sovrapposizione. I componenti sono raggruppati in base ai rispettivi tipi di componenti. I componenti uguali in entrambe le righe saranno di carattere normale. Non sarà possibile confrontare le righe di due soluzioni.
