---
sidebar: sidebar 
permalink: working-with-ontap-san-host-solutions-search.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network 
summary: Verifica la compatibilità per la versione di ONTAP e le combinazioni di versioni di storage Flash o Fabric. È possibile perfezionare ulteriormente la ricerca di compatibilità per ogni componente rilevante 
---
= Utilizzo di ONTAP SAN host Ricerca semplificata
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Verifica la compatibilità per la versione di ONTAP e le combinazioni delle versioni di storage Flash o Fabric. È possibile perfezionare ulteriormente la ricerca di compatibilità per ogni componente rilevante.



== A proposito di questa attività

Puoi verificare la compatibilità tra i dispositivi di storage Flash o Fabric sulla tua SAN con la versione di ONTAP che desideri utilizzare e altri componenti rilevanti. È possibile scegliere tra *Vista Esperti* o *Vista Novizio*.


NOTE: Fare clic sull'opzione *Imposta come predefinita* per aprire automaticamente una ricerca *host SAN ONTAP semplificato* ogni volta che si apre IMT.



== Fasi

. Fare clic su *ONTAP SAN host Simplified* nella home page.
. Selezionare la vista che si desidera utilizzare:
+
.. Fare clic su *Vista esperto* per visualizzare le opzioni dei criteri avanzati.
.. Fare clic su *Vista guidata* per visualizzare le opzioni dei criteri semplificati e guidati.


. In *Vista principianti*, selezionare le opzioni dei criteri di ricerca visualizzate.
+
.. Fare clic su *Ignora* per passare al componente successivo senza effettuare una selezione. È possibile tornare al componente facendo clic su *Unskip* secondo necessità.
.. Al termine, fare clic su *Visualizza risultati* per visualizzare le configurazioni supportate per i criteri di ricerca.


. In *Vista Esperti*, selezionare i criteri di ricerca che si desidera utilizzare per i vari componenti. Si consiglia di spostarsi da sinistra a destra in quanto ciascuna selezione affina i criteri rimanenti. Non è necessario effettuare una selezione per ogni componente.
+
.. Al termine, fare clic su *Visualizza risultati* per visualizzare le configurazioni supportate per i criteri di ricerca.


. È inoltre possibile effettuare le seguenti operazioni come parte di *ONTAP SAN host Simplified*:
+
.. Fare clic sull'icona del libro per visualizzare la politica e le linee guida applicabili alla selezione effettuata.
.. Fare clic sull'icona della catena per generare un URL condivisibile per le selezioni che è possibile condividere con altri utenti.
.. Selezionare l'icona Annulla per cancellare tutte le selezioni e ricominciare.


. Dalla schermata dei risultati, è possibile effettuare le seguenti operazioni:
+
.. Visualizzare dettagli, avvisi e note informative sulla configurazione in uso.
.. Fare clic sull'icona a forma di stella per rendere la ricerca preferita. Assegnare un nome e descrivere la configurazione. Questa operazione diventa una ricerca salvata, visualizzabile dal menu *Ricerca salvata*. È anche possibile sottoscrivere la configurazione qui, in modo da ricevere una notifica quando vengono apportate modifiche. Se si effettua la sottoscrizione, questo verrà visualizzato anche nel menu *Sottoscrizioni*.
.. Passare il mouse sopra la vista *build end-to-end con* per trovare ulteriori soluzioni supportate.
.. Fare clic su *cosa succede se* per modificare i componenti ed esplorare altre opzioni di compatibilità.



